### ISSUE TITLE
website + registry: Use GitHub Flavored Markdown for README rendering

### ISSUE THREAD

**Issue by MylesBorins** [npm/roadmap#15]
**Summary**

The npm website does not currently render READMEs with GitHub flavored Markdown. This can create an inconsistency between viewing the document on GitHub and viewing it on npmjs.com.

**Intended Outcome**

During publishing we would render markdown in a way that respects GitHub flavored Markdown. We may possibly want to re-render existing READMEs

**How will it work?**

This is a feature that should _just work™️_ when developers publish modules to the registry.

**References**

This feature was originally requested in https://github.com/npm/feedback/discussions/3

**Comment by ethomson** [comment]
[npm is now using GitHub Flavored Markdown](https://github.blog/changelog/2020-12-01-npm-uses-github-flavored-markdown/) for rendering READMEs on npmjs.com.  New packages being published should have READMEs that render identically between GitHub and npmjs.com (barring, of course, some differences in the theming, like colors and default fonts).

Since rendered READMEs are cached, you will not see any changes to existing packages immediately.  We'll work our way through the backlog of existing packages and re-render the READMEs with GFM.  So these will get updated over time.
